name: Github Action
on:
  # Action On
  pull_request:
    branches:
    - master
jobs:
  # Build
  build:
    name: Build
    strategy:
      matrix:
        java-version: [1.7]
        os: [ubuntu-latest, windows-latest, macos-latest]
          
    runs-on: ${{ matrix.os }}
    steps:
      # Installing Matrix OS Dependencies
      - name: Install dependencies ${{ matrix.os }}
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update
      - name: Install dependencies ${{ matrix.os }}
        if: matrix.os == 'windows-latest'
        run: choco install git
      - name: Install dependencies ${{ matrix.os }}
        if: matrix.os == 'macos-latest'
        run: brew install git
      # Get Sources
      - name: Checkout sources control
        uses: actions/checkout@v1
      # Setup Environment
      - name: Setup java version $ {{ matrix.java-version }} 
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          java-package: jdk
          architecture: x64
      # Runner
      - name: Running Environment
        run: |
          java -version
  # Deployment
  deploy:
    name: Deploying
    needs: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Running Environment
        run: |
          java -version
