name: Node JS Action
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    name: Main
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          node-version: [10]
          os: [ubuntu-latest]
    steps:
    - name: Prepare
      uses: actions/checkout@v1
    - name: Set Up Node JS
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.java-version }}